services:
  psn_bot:
    container_name: psn-bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
    ports:
      - "8000:8000"

  psn_parser:
    container_name: psn-parser
    build:
      context: ./parsing
      dockerfile: Dockerfile
    volumes:
      - ./parsing:/app
    ports:
      - "7000:8000"

