services:
  psn_bot:
    container_name: psn-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app

  psn_parser:
    container_name: psn-parser
    build:
      context: ./parsing
      dockerfile: Dockerfile
    volumes:
      - ./parsing:/app

