services:
  psn_bot:
    container_name: psn-bot
    build:
      context: ./bot
      dockerfile: Dockerfile
    volumes:
      - ./bot:/app
    ports:
      - "8000:8000"
    networks:
      - psn-network

  psn_parser:
    container_name: psn-parser
    build:
      context: ./parsing
      dockerfile: Dockerfile
    volumes:
      - ./parsing:/app
    ports:
      - "7000:8000"
      - "9000:9000"
      - "443:443"
    networks:
      - psn-network

networks:
  psn-network:
    driver: bridge

